import pandas as pd

data = {
    "query": [
        "How can I book a flight online?",
        "What is the baggage allowance for domestic flights?",
        "Can I change my flight date after booking?",
        "How do I request a refund for a cancelled flight?",
        "What are the check-in procedures at Lagos airport?",
        "Do you offer in-flight meals on international flights?",
        "Is there a loyalty program for frequent flyers?",
        "Can I carry a pet on board your flights?",
        "What documents do I need for international travel?",
        "How early should I arrive at the airport before departure?",
        "How do I contact customer service for assistance?",
        "What are the COVID-19 travel requirements for Ibom Airline?",
        "Can I get a seat upgrade to business class?",
        "How do I access the airport lounge at Abuja airport?",
        "What are the available payment options for booking tickets?",
        "Is there Wi-Fi available on your flights?",
        "How do I track the status of my flight?",
        "Can I cancel my flight booking online?",
        "Do you provide special assistance for disabled passengers?",
        "What are the routes operated by Ibom Airline?",
        "How can I check my flight schedule and timings?",
        "What is your policy on flight delays and compensations?",
        "Can I purchase travel insurance with my ticket?",
        "What is the procedure for reporting lost baggage?",
        "Are there any discounts available for group bookings?",
        "How can I make changes to my reservation?",
        "What are the terms and conditions for ticket refunds?",
        "Do you offer student discounts on flight tickets?",
        "How do I earn and redeem loyalty points?",
        "What are the rules for carrying sports equipment?",
        "Can I book an extra seat for additional comfort?",
        "What is the fee for excess baggage?",
        "How do I update my contact information in my booking?",
        "Are there any special meals available for dietary restrictions?",
        "Can I travel with an infant? What are the requirements?",
        "How can I book a flight using my loyalty points?",
        "What should I do if my flight is delayed?",
        "Do you offer any holiday packages?",
        "What are the carry-on baggage restrictions?",
        "How can I check in online for my flight?",
        "Are there any vaccination requirements for international travel?",
        "Can I request a specific seat during booking?",
        "How do I cancel my flight and get a refund?",
        "What are the procedures for missed flights?",
        "Can I reschedule my flight to a later date?",
        "What are the baggage allowances for infants?",
        "How can I provide feedback about my flight experience?",
        "Is there a mobile app for managing my bookings?"
    ],
    "category": [
        "booking",
        "baggage",
        "booking",
        "refund",
        "check-in",
        "services",
        "loyalty",
        "baggage",
        "travel_documents",
        "check-in",
        "contact",
        "health",
        "services",
        "services",
        "payment",
        "services",
        "flight_status",
        "booking",
        "special_assistance",
        "routes",
        "flight_status",
        "policy",
        "services",
        "baggage",
        "booking",
        "booking",
        "refund",
        "discounts",
        "loyalty",
        "baggage",
        "services",
        "baggage",
        "booking",
        "services",
        "travel_with_infant",
        "loyalty",
        "flight_status",
        "services",
        "baggage",
        "check-in",
        "health",
        "services",
        "refund",
        "policy",
        "booking",
        "baggage",
        "feedback",
        "services"
    ]
}

df = pd.DataFrame(data)
df.to_csv('customer_support_data.csv', index=False)
